config/routes.rb
LeaveTracker::Application.routes.draw do
  resources :leavedates, only: [:create, :destroy, :new, :show, :edit, :update]

  devise_for :users
  resources :users, :only => [:show]
  root  to: 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/edit_leave', to:'leavedates#add_leavedate', via: 'get'
  match '/show_user', to:'leavedates#show_user', via: 'get'
  match '/all_users', to:'leavedates#show_users', via: 'get'
  match '/show_leaves', to:'leavedates#show', via: 'get'
  match 'users/:id' => 'users#show', via: :get
  

end

app/models/leavedate.rb
class Leavedate < ActiveRecord::Base
	attr_accessible :user_id, :date, :description
	belongs_to :user
	validates :date, :uniqueness => { :scope => :user_id }
	validates :date, presence: true
	validate :date_cannot_be_in_the_past
	validate :date_cannot_be_in_weekend
	validates :user_id, presence: true
	default_scope order: 'leavedates.date ASC'

	def date_cannot_be_in_the_past
		errors.add(:date, "has already passed") if !date.blank? and date < Date.today 
	end
	def date_cannot_be_in_weekend
		errors.add(:date, "is in a weekend") if date.saturday? or date.sunday?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  has_many :leavedates, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def mohit
    @leavedates||=current_user.leavedates
  end
end

app/controllers/leavedates_controller.rb
class LeavedatesController < ApplicationController

#before_filter :user_signed_in
before_filter :correct_user,   only: :destroy
  def create
  	date = Date.strptime(params[:leavedate][:date], "%m/%d/%Y")
    @leavedate = current_user.leavedates.build(date: date, description: params[:leavedate][:description])
    #puts @leavedate.date
    if @leavedate.save
      flash[:success] = "Leave created!"
      redirect_to root_url
    else
      #@leavedate.destroy
      #debugger
      render 'leavedates/add_leavedate'
    end
  end
  
  def destroy
    @leavedate.destroy
    #@x = @leavedate.user.leavedates.count
    respond_to do |format|
      format.html { 
        #user = User.find(@post.user_id)
        #redirect_to @user 
      }
      format.js
    end
    #redirect_to root_url
  end

def show
  #debugger
	#@leavedate ||= Leavedate.new
end

def edit
    @leavedate = Leavedate.find(params[:id])
    #redirect_to root_url
  end

  def update
    @leavedate = Leavedate.find(params[:id])
    date = Date.strptime(params[:leavedate][:date], "%m/%d/%Y")
    if @leavedate.update_attributes(date: date, description: params[:leavedate][:description])
      # Handle a successful update.
      flash[:success] = "Update successful"
      redirect_to root_url
    else
      flash[:error] = "Update failed"
      render 'edit'
    end
  end
private
  
    def correct_user
      @leavedate = current_user.leavedates.find_by_id(params[:id])
      redirect_to root_url if @leavedate.nil?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		#@leavedate = current_user.leavedates if user_signed_in?
		@leavedates = current_user.leavedates
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Leave Tracker"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def initial_authenticate
  	if signed_in?
  		authenticate_user!
  	end
  end
end

app/helpers/leavedates_helper.rb
module LeavedatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  <div class="link">
    <a href="http://chronus.com/">Chronus Corporation</a>
   </div>
  </small>
  <nav>
    <ul>
      <li class="link"><%= link_to "About",   about_path %></li>
      <li class="link"><%= link_to "Help",    help_path %></li>
      <li class="link"><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Leave Tracker", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">

          <li><%= link_to "Home",    root_path %></li>
          
          <!--<li><%= link_to "Sign in", '#' %></li>-->
          
            <% if user_signed_in? %>
            <li> <p class="navbar-text">
              <%= link_to "All Users", all_users_path, :class => 'navbar-link' %>  &nbsp
            </p></li>
            <li><p class="navbar-text">
              <%= link_to "Upcoming Leaves ", show_leaves_path, class: "navbar-link" %> |
            </p></li>
           <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Logged in as <strong><%= current_user.email %></strong>.<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |</li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
        <%flash.delete(:notice)%>
      <% end %>
      <% if alert %>
      
        <p class="alert alert-danger"><%= alert %></p>
        <%flash.delete(:alert)%>
      <% end %>
      
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/leavedates/_leavedate.html.erb
<%if leavedate.date && leavedate.created_at and leavedate.date>=Date.today %>
<tr id=<%="leave" + leavedate.id.to_s%>>
<td>
  <span class="date"><%= leavedate.date.inspect %></span></td>
  <td>
  <div>
  <span class="content"><%= leavedate.description %></span>
  </div>
  </td>
  <% if current_user == leavedate.user %>
  <td>
  <div>
    <%= link_to content_tag(:i, "", class: "icon-remove icon-black") + "Delete", leavedate, method: :delete,remote: true,
                                     data: { confirm: "You sure?" },
                                     title: leavedate.date.inspect, class: "remove_fields btn", style: "margin:3px" %>
    <%= link_to content_tag(:i, "", class: "icon-edit icon-black") +  "Edit", edit_leavedate_path(leavedate), class: "remove_fields btn" ,  style: "margin:4px" %>
  </div>
  </td>
  <% end %>
</tr>
<%end%>

app/views/leavedates/_leavedate_form.html.erb
<script type='text/javascript'>
$(function() {
  $('.datepicker').datepicker();
  $(".datepicker").datepicker('setDate', new Date());
});
</script>

<div>
<h3> Edit Leaves </h3>
<div class="errors">
The following are the error messages.
<%= render 'shared/error_messages' %>
</div>
</div>
<% @leavedate = current_user.leavedates.build %>
<%= form_for(@leavedate) do |f| %>
	
  <div class="field">
    <%= f.text_field :date, :class => "datepicker" , values: Date.today.strftime( "%m/%d/%Y" ), autofocus: true%>
  </div>
  <div><%= f.label :description %><br />
  <%= f.text_area :description, autofocus: true, placeholder: "Add description..." %></div>

  <%= f.submit "Add Leave", class: "btn btn-large btn-primary" %>
<% end %>

app/views/leavedates/_show_leave.html.erb
<%if leavedates and leavedates.count>0 %>
<tr>
<td>
  <span class="date"><%= leavedates[0].date.inspect %></span></td>
  <td>
  <div>
  <ul>
  <%for i in 0..(leavedates.count-1) do%>
    <li><span class="content"><%= leavedates[i].user.name %></span></li>
  <%end%>
  </ul>
  </div>
  </td>
</tr>
<%end%>

app/views/leavedates/_show_leavedates.html.erb
<% @leavedates ||= current_user.leavedates %>
  <div class="hero-unit">

    <% if @leavedates.any? and @leavedates.first.date? and (@leavedates.last.date==nil or @leavedates.last.date>=Date.today)%>

      <h3 style="margin:40px" id="upcoming">Upcoming Leaves</h3>
      <table class="table table-striped table-condensed table-bordered" style="background:#fff" >
      <th style="width:200px">
      	Date
      </th>
      <th style="width:300px">
      	Description
      </th>
      <% if @leavedates.first and @leavedates.first.user and current_user == @leavedates.first.user %>
      <th style="width:300px">
      	Actions
      </th>
      <%end%>
        <%= render @leavedates %>
      </table>
    <% else %>
      No leaves to show.
    <% end %>
    
</div>

app/views/leavedates/add_leavedate.html.erb
<%= render 'leavedates/leavedate_form' %>

app/views/leavedates/destroy.js.erb
$("#leave"+<%= @leavedate.id%>).remove();
$('div.alert').remove()

app/views/leavedates/edit.html.erb
<% provide(:title, "Edit Leave") %>
<h1>Update your leave</h1>

<script type='text/javascript'>
$(function() {
  $('.datepicker').datepicker();
  $(".datepicker").datepicker('setDate', new Date());
});
</script>

<div>
<h3> Edit Leave </h3>
<div class="errors">
The following are the error messages.

</div>
</div>
<%= form_for(@leavedate) do |f| %>
  <%= render 'shared/error_messages'%>
  
  <div class="field">
    <%= f.text_field :date, :class => "datepicker" , values: Date.today.strftime( "%m/%d/%Y" ), autofocus: true%>
  </div>
  <div><%= f.label :description %><br />
  <%= f.text_area :description, autofocus: true, placeholder: "Add description..." %></div>

  <%= f.submit "Edit Leave", class: "btn btn-large btn-primary" %>
<% end %>

app/views/leavedates/show.html.erb
  <div class="hero-unit">

      <h3 style="margin:40px" id="upcoming">Upcoming Leaves within 2 weeks</h3>
      <table class="table table-striped table-condensed table-bordered" style="background:#fff" >
      <th style="width:200px">
      	Date
      </th>
      <th style="width:300px">
      	Name
      </th>
      <% for i in 0..13 do%>
        <%leavedates = Leavedate.find(:all, :conditions => [ "date = ?", Date.today + i])%>
        <%=render partial: "show_leave", locals: {leavedates: leavedates}%>
      <%end %>
      </table>
  </div>

app/views/leavedates/show_users.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<% @users = User.all %>
<ul class="users">
  <% @users.each do |user| %>
    <li class="link1">
      <%= link_to user.name.to_s+" <"+user.email.to_s+">", "users/"+user.id.to_s%>
    </li>
  <% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if @leavedate and @leavedate.errors and @leavedate.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@leavedate.errors.count, "error") %>.
    </div>
    <ul>
    <% @leavedate.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
  This is an application for tracking the leaves of the employees of a company.
  Generally when employees take leave the other employees don't know about it.
  This causes problems as people are not able to plan accordingly. This application
  helps people to track which all people are absent on a particular day so that they
  can make their plans accordingly.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Mohit Aggarwal (mohit.829[at]google[dot]com)
  <a href="http://chronus.com/about-us/contact-us">Chronus Contact Page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Describe the usage of the application here.
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
<div class="center">
<h3>Welcome <strong><%= current_user.name %></strong></h3>
</div>
<%= render 'leavedates/show_leavedates' %>
<div class="center">
<%= link_to "Want to add leaves?", edit_leave_path, class: "center btn btn-large" %>
</div>
<% else %>
<div class="center hero-unit">
  <h1>Welcome to the Leave Tracker</h1>

  <h2>
    This is the home page for the Leave Tracker.
  </h2>
</div>
<% end %>

app/views/users/show.html.erb
<h3>
<%=@user.name%>
</h3>
<% @leavedates = @user.leavedates %>
<%= render 'leavedates/show_leavedates' %>